name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  frontend-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14' # Replace with your Node.js version

    - name: Install Dependencies
      run: npm install
      working-directory: ./mta

    - name: Run Tests
      run: npm test
      working-directory: ./mta

    - name: Build the Docker image
      run: docker build ./dockerserver --file ./dockerserver/Dockerfile --tag my-image-name:$(date +%s)
        
  backend-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install backend dependencies
      run: npm install
      working-directory: ./ec2
    - name: Run backend tests
      run: npm test
      working-directory: ./ec2
